# wrangler.toml — Sporty
name = "sporty"
main = "src/worker.js"
compatibility_date = "2025-09-07"
account_id = "3163c47e268d21d781c4fd86a71964cb"

assets = { directory = "./site" }

# --- Default/local (wrangler dev) ---
workers_dev = true  # enables local + a workers.dev preview when not using a specific env

# --- Staging (preview env) ---
[env.staging]
workers_dev = true   # get a workers.dev URL on deploy (no custom domain)
# You can add staging-specific vars/bindings here later, e.g.:
# [env.staging.vars]
# API_BASE = "https://staging-api.example.com"

# --- Production ---
[env.production]
# bind to the real domain
routes = [
  { pattern = "sporty.plyml.com/*", zone_name = "plyml.com" }
]
# [env.production.vars]
# API_BASE = "https://api.plyml.com"
